카카오 소셜 로그인(OAuth 2.0) 개발
backtothefuture-team/backtothefuture-backend pull request #20
Opened 2024-03-05 16:21 UTC by Lee-Sang-Min1998

## 📝 작업 내용
 - OAuth 2.0을 사용한 로그인(카카오, 네이버) 중 카카오 소셜 로그인(OAuth 2.0)을 개발했습니다. 
 - 비회원인 경우 카카오 로그인 API에서 회원 가입을 진행시킨 후 토큰을 반환하도록 했습니다.

## 💬 ETC.
 - Restemplate은 deprecated 되어 Webclient을 사용하여 외부 API를 호출하였습니다.
 -  현재 카카오 애플리케이션에 테스트앱을 등록하여 비즈앱처럼 사용이 가능하고 닉네임, 프로필 사진, 카카오계정(이메일, 전화번호), 이름, 성별을 필수 동의 항목으로 설정하였습니다.
- **미흡한점**

1.  새로운 인증 코드를 매 로그인 요청마다 받아오고 그것을 이용하여 백엔드에서 구현한 access token을 발급 받아야 하는데 해당 프로세스에 대해 테스트 코드를 어떻게 작성해야 할 지 고민입니다. 이로 인해 아직 테스트 코드 + 명세서를 작성하지 못했습니다

## #️⃣ 연관된 이슈
resolve: #5

2024-03-05 21:41 UTC, seongolee requested changes
1. record를 사용해서 dto를 사용하는 부분이 반영이 안된 것 같습니다.
2. 테스트 케이스의 경우 본인인증하는 부분은 고려하지않고, 본인인증 된 후 서버로 넘어오는 부분부터 mockito로 작성해서 처리하면 될 것 같습니다.

2024-03-06 02:08 UTC, Lee-Sang-Min1998 commented
> 1. dto 생성시 record로 사용하는 부분이 반영이 안된 것 같습니다.
> 2. 테스트 케이스의 경우 본인인증하는 부분은 고려하지않고, 본인인증 된 후 서버로 넘어오는 부분부터 mockito로 작성해서 처리하면 될 것 같습니다.

1. 네 반영하겠습니다
2. 그러면 사용자 정보를 받아 왔다고 가정하고 그 이후부터 테스트를 진행하면 될까요?

2024-03-06 03:49 UTC, seongolee commented
그러면 사용자 정보를 받아 왔다고 가정하고 그 이후부터 테스트를 진행하면 될까요?
> 넵 저는 그렇게 생각합니다.

2024-03-06 04:24 UTC, Lee-Sang-Min1998 commented
> 그러면 사용자 정보를 받아 왔다고 가정하고 그 이후부터 테스트를 진행하면 될까요?
> 
> > 넵 저는 그렇게 생각합니다.
> 
> * RolesType Exception 핸들링에 대해서도 코멘트 남겨두었습니다.

혹시 리뷰 확인이 안되는데 어디에 있나요?ㅠㅠ

2024-03-06 04:25 UTC, Lee-Sang-Min1998 commented
> 그러면 사용자 정보를 받아 왔다고 가정하고 그 이후부터 테스트를 진행하면 될까요?
> 
> > 넵 저는 그렇게 생각합니다.
> 
> * RolesType Exception 핸들링에 대해서도 코멘트 남겨두었습니다.

RolesType Exception 핸들링 리뷰가 확인이 안되는데 혹시 어디서 확인이 가능할까요?ㅜㅜ

2024-03-06 06:43 UTC, closed without merging

2024-03-06 08:30 UTC, Lee-Sang-Min1998 commented on api/member/src/main/java/com/backtothefuture/member/exception/GlobalExceptionHandler.java
> +        log.warn(">>>>> OAuthException : {}", ex);
아 그렇네요! 수정하겠습니다 :)